#!/bin/bash

export WPCD_USER=##WPCD_USER##
export AI_PROMPT=##AI_PROMPT##
export AI_SAMPLES=##AI_SAMPLES##
export AI_OUTPUT_DIR=##AI_OUTPUT_DIR##
export AI_STEPS=##AI_STEPS##
export AI_WIDTH=##AI_WIDTH##
export AI_HEIGHT=##AI_HEIGHT##
export AI_SEED=##AI_SEED##
export CALLBACK_URL=##CALLBACK_URL##
export CALLBACK_URL_ALT=##CALLBACK_URL_ALT##
export SERVER_ID=##SERVER_ID##
export APP_ID=##APP_ID##
export TASK_ID=##TASK_ID##
